version: '3.8'

services:
  db:
    container_name: mysql
    # image: mysql:8.0.29-oracle
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=memic
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: