-- Create new tables
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE phrase (
    end_index INTEGER NOT NULL,
    start_index INTEGER NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT,
    sentence_id BIGINT,
    meaning VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE phrase_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    phrase_id BIGINT,
    tag_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE recognized_sentence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE recognized_sentence_recognized_words (
    recognized_sentence_id BIGINT NOT NULL,
    recognized_words_id BIGINT NOT NULL UNIQUE
);

CREATE TABLE recognized_word (
    is_matched_with_transcription BOOLEAN NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    word VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE transcription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    url VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE transcription_sentence (
    start_point TIME(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transcription_id BIGINT NOT NULL,
    content VARCHAR(255),
    PRIMARY KEY (id)
);

-- Add foreign keys
ALTER TABLE phrase
    ADD CONSTRAINT FKmb41tcl8a3v2g2ti6cspjqb5
        FOREIGN KEY (member_id)
            REFERENCES member(id);

ALTER TABLE phrase
    ADD CONSTRAINT FK7lhslobro17xsedunlh8mf1pw
        FOREIGN KEY (sentence_id)
            REFERENCES transcription_sentence(id);

ALTER TABLE phrase_tag
    ADD CONSTRAINT FK8c5y4oo6en4pfatsi4tmd9d5h
        FOREIGN KEY (phrase_id)
            REFERENCES phrase(id);

ALTER TABLE phrase_tag
    ADD CONSTRAINT FKjyv9quiex6ra82nfhdm87sm5i
        FOREIGN KEY (tag_id)
            REFERENCES tag(id);

ALTER TABLE recognized_sentence_recognized_words
    ADD CONSTRAINT FKnjdqkupma2wrgvdcbjaktxiit
        FOREIGN KEY (recognized_words_id)
            REFERENCES recognized_word(id);

ALTER TABLE recognized_sentence_recognized_words
    ADD CONSTRAINT FK96p452p6xp7qhmib62v0wae7p
        FOREIGN KEY (recognized_sentence_id)
            REFERENCES recognized_sentence(id);

ALTER TABLE transcription_sentence
    ADD CONSTRAINT FK3xgxgwi7auednfem1g9tvpjmv
        FOREIGN KEY (transcription_id)
            REFERENCES transcription(id);
